"""Tests for the detection of responses broken by a TLS-intercepting proxy."""

from __future__ import annotations

import dataclasses
from typing import Any

import pytest

from crawl4tools.engine.interception import (
    Interference,
    InterferenceSign,
    detect_interference,
    is_tls_message,
)

SQUID_TITLE = "ERROR: The requested URL could not be retrieved"


def squid_page(code: str | None = "ERR_SECURE_CONNECT_FAIL", title: str = SQUID_TITLE) -> str:
    """Return an error page shaped like Squid's stock templates."""
    body = f"<body id={code}>" if code is not None else "<body>"
    return (
        '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">\n'
        "<html><head>\n"
        '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n'
        f"<title>{title}</title>\n"
        "</head>"
        f"{body}\n"
        "<div id=titles><h1>ERROR</h1></div>\n"
        "</body></html>"
    )


ORDINARY_PAGE = "<html><head><title>Example Domain</title></head><body>Hi</body></html>"


# --- S1: TLS-layer errors ---------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        "Page.goto: net::ERR_SSL_PROTOCOL_ERROR at https://example.com/",
        "Error: Failed on navigating ACS-GOTO:\nPage.goto: net::ERR_CERT_AUTHORITY_INVALID at x",
        "net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH",
        "net::ERR_CERT_COMMON_NAME_INVALID",
        "net::ERR_BAD_SSL_CLIENT_AUTH_CERT",
        "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: "
        "self-signed certificate in certificate chain (_ssl.c:1000)",
        "certificate verify failed: unable to get local issuer certificate",
        "[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)",
        "wrong version number",
        "[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)",
        "sslv3 alert handshake failure",
        "SSL handshake failed",
        "PAGE.GOTO: NET::ERR_SSL_PROTOCOL_ERROR",
    ],
    ids=[
        "browser-ssl-protocol-error",
        "browser-cert-authority-invalid-wrapped",
        "browser-ssl-cipher-mismatch",
        "browser-cert-common-name",
        "browser-bad-client-auth-cert",
        "httpx-certificate-verify-failed",
        "httpx-certificate-verify-failed-without-prefix",
        "httpx-wrong-version-number",
        "httpx-wrong-version-number-without-prefix",
        "httpx-tlsv1-alert",
        "httpx-sslv3-alert",
        "ssl-handshake",
        "uppercase",
    ],
)
def test_tls_messages_are_recognized(text: str) -> None:
    assert is_tls_message(text) is True


@pytest.mark.parametrize(
    "text",
    [
        None,
        "",
        "net::ERR_PROXY_CONNECTION_FAILED at https://example.com/",
        "net::ERR_TUNNEL_CONNECTION_FAILED",
        "net::ERR_NAME_NOT_RESOLVED at https://example.com/",
        "net::ERR_CONNECTION_REFUSED at https://tls.example/ssl/cert",
        "Timeout 30000ms exceeded.",
        "[Errno 61] Connection refused",
        "Blocked by anti-bot protection: HTTP 403 with HTML content (5000 bytes)",
    ],
    ids=[
        "none",
        "empty",
        "proxy-connection-failed",
        "tunnel-failed",
        "name-not-resolved",
        "tls-and-ssl-only-in-the-url",
        "timeout",
        "httpx-connection-refused",
        "crawl4ai-anti-bot",
    ],
)
def test_other_messages_are_not_tls(text: str | None) -> None:
    assert is_tls_message(text) is False


# --- S2: an error page generated by the proxy --------------------------------------


@pytest.mark.parametrize(
    ("headers", "status_code"),
    [
        ({"X-Squid-Error": "ERR_SECURE_CONNECT_FAIL 0"}, 503),
        ({"x-squid-error": "ERR_SECURE_CONNECT_FAIL 0"}, 503),
        ({"X-SQUID-ERROR": "ERR_SECURE_CONNECT_FAIL 0"}, None),
        ({"X-Squid-Error": "ERR_SECURE_CONNECT_FAIL 0"}, 200),
    ],
    ids=["canonical-name", "lowercase-name", "uppercase-name-unknown-status", "status-200"],
)
def test_squid_error_header_is_a_proxy_error_page(
    headers: dict[str, str], status_code: int | None
) -> None:
    assert detect_interference(headers, "", status_code) == Interference(
        InterferenceSign.PROXY_ERROR_PAGE, "ERR_SECURE_CONNECT_FAIL 0"
    )


def test_squid_error_header_detail_is_stripped() -> None:
    found = detect_interference({"X-Squid-Error": "  ERR_CONNECT_FAIL 111 "}, None, 503)
    assert found == Interference(InterferenceSign.PROXY_ERROR_PAGE, "ERR_CONNECT_FAIL 111")


@pytest.mark.parametrize("status_code", [503, 403, 400, 599, None])
def test_squid_title_with_an_error_status_is_a_proxy_error_page(status_code: int | None) -> None:
    found = detect_interference({"content-type": "text/html"}, squid_page(), status_code)
    assert found == Interference(InterferenceSign.PROXY_ERROR_PAGE, "ERR_SECURE_CONNECT_FAIL")


def test_squid_title_without_an_error_code_reports_the_title() -> None:
    found = detect_interference({}, squid_page(code=None), 503)
    assert found == Interference(InterferenceSign.PROXY_ERROR_PAGE, SQUID_TITLE)


def test_squid_title_is_matched_with_normalized_whitespace_and_case() -> None:
    html = squid_page(title="\n  error:   The requested URL\n could NOT be retrieved ")
    found = detect_interference(None, html, 503)
    assert found is not None
    assert found.sign is InterferenceSign.PROXY_ERROR_PAGE


def test_squid_title_with_escaped_characters_is_matched() -> None:
    html = squid_page(title="ERROR:&#32;The requested URL could not be retrieved")
    found = detect_interference(None, html, 503)
    assert found is not None
    assert found.sign is InterferenceSign.PROXY_ERROR_PAGE


@pytest.mark.parametrize("status_code", [200, 204, 301, 399])
def test_squid_title_with_a_success_status_is_not_interference(status_code: int) -> None:
    assert detect_interference({"content-type": "text/html"}, squid_page(), status_code) is None


def test_other_title_with_an_error_status_is_not_interference() -> None:
    assert detect_interference({}, squid_page(title="Service Unavailable"), 503) is None


def test_squid_title_outside_the_title_element_is_not_interference() -> None:
    html = f"<html><head><title>Squid FAQ</title></head><body><p>{SQUID_TITLE}</p></body></html>"
    assert detect_interference({}, html, 503) is None


POLICY_DENIALS = [
    "ERR_ACCESS_DENIED",
    "ERR_CACHE_ACCESS_DENIED",
    "ERR_FORWARDING_DENIED",
    "ERR_CACHE_MGR_ACCESS_DENIED",
]


@pytest.mark.parametrize("code", POLICY_DENIALS)
def test_policy_denial_header_is_not_interference(code: str) -> None:
    # The administrator refused the request: never treat it as a broken proxy.
    headers = {"X-Squid-Error": f"{code} 0"}
    assert detect_interference(headers, squid_page(code=code), 403) is None


@pytest.mark.parametrize("code", POLICY_DENIALS)
def test_policy_denial_header_wins_over_a_non_denial_page(code: str) -> None:
    headers = {"X-Squid-Error": f"{code} 0"}
    assert detect_interference(headers, squid_page(code="ERR_SECURE_CONNECT_FAIL"), 403) is None


@pytest.mark.parametrize("code", POLICY_DENIALS)
def test_policy_denial_header_without_the_status_suffix_is_not_interference(code: str) -> None:
    assert detect_interference({"x-squid-error": code}, None, 403) is None


@pytest.mark.parametrize("code", POLICY_DENIALS)
def test_policy_denial_page_without_the_header_is_not_interference(code: str) -> None:
    # The header can be removed by the administrator; the page still names the error.
    assert detect_interference({}, squid_page(code=code), 403) is None


@pytest.mark.parametrize("value", ["", "   "], ids=["empty-header", "blank-header"])
def test_empty_squid_error_header_falls_back_to_the_title(value: str) -> None:
    headers = {"X-Squid-Error": value}
    assert detect_interference(headers, ORDINARY_PAGE, 503) is None
    found = detect_interference(headers, squid_page(), 503)
    assert found == Interference(InterferenceSign.PROXY_ERROR_PAGE, "ERR_SECURE_CONNECT_FAIL")


# --- S3: a bot challenge ---------------------------------------------------------------


@pytest.mark.parametrize(
    "headers",
    [
        {"cf-mitigated": "challenge"},
        {"CF-Mitigated": "challenge"},
        {"CF-MITIGATED": "Challenge"},
        {"cf-mitigated": "  challenge "},
    ],
    ids=["lowercase", "canonical-name", "uppercase-name-and-value", "padded-value"],
)
def test_cloudflare_challenge_header_is_a_bot_challenge(headers: dict[str, str]) -> None:
    found = detect_interference(headers, "<html><title>Just a moment...</title></html>", 403)
    assert found == Interference(InterferenceSign.BOT_CHALLENGE, "challenge")


def test_cloudflare_challenge_header_is_found_whatever_the_status() -> None:
    found = detect_interference({"cf-mitigated": "challenge"}, None, None)
    assert found == Interference(InterferenceSign.BOT_CHALLENGE, "challenge")


def test_other_cf_mitigated_value_is_not_interference() -> None:
    assert detect_interference({"cf-mitigated": "something-else"}, None, 403) is None


# --- nothing to see ----------------------------------------------------------------------


@pytest.mark.parametrize(
    ("headers", "html", "status_code"),
    [
        (None, None, None),
        ({}, "", 200),
        ({"content-type": "text/html", "server": "cloudflare"}, ORDINARY_PAGE, 200),
        ({"via": "1.1 squid (squid/6.10)"}, ORDINARY_PAGE, 200),
        ({"via": "1.1 squid (squid/6.10)"}, ORDINARY_PAGE, 404),
        ({"x-squid-error": None}, None, 503),
    ],
    ids=[
        "nothing",
        "empty",
        "ordinary-page",
        "page-through-squid",
        "error-page-of-the-site-through-squid",
        "header-without-value",
    ],
)
def test_ordinary_responses_are_not_interference(
    headers: dict[str, Any] | None, html: str | None, status_code: int | None
) -> None:
    assert detect_interference(headers, html, status_code) is None


def test_interference_is_frozen() -> None:
    found = Interference(InterferenceSign.BOT_CHALLENGE, "challenge")
    with pytest.raises(dataclasses.FrozenInstanceError):
        found.detail = "x"  # type: ignore[misc]


# --- untrusted HTML -------------------------------------------------------------------------


def test_unclosed_squid_title_is_not_interference() -> None:
    html = f"<html><head><title>{SQUID_TITLE}"
    assert detect_interference({}, html, 503) is None


def test_many_unclosed_tags_are_not_interference() -> None:
    # Repeated openings without a closing ">" must not make the search blow up.
    html = "<title <body id=" * 50_000
    assert detect_interference({}, html, 503) is None


def test_squid_title_far_down_the_page_is_not_searched() -> None:
    # Only the start of a page is searched; a proxy's error page has its title there.
    html = "<!--" + "x" * 70_000 + "-->" + squid_page()
    assert detect_interference({}, html, 503) is None


def test_squid_code_after_a_large_head_is_found_within_the_searched_start() -> None:
    html = squid_page().replace("</head>", "<style>" + "x" * 20_000 + "</style></head>")
    found = detect_interference({}, html, 503)
    assert found == Interference(InterferenceSign.PROXY_ERROR_PAGE, "ERR_SECURE_CONNECT_FAIL")
